In [2]:
import numpy as np

In [4]:
print(np.arange(1, 10, 0.3))
print(np.arange(20))
print(np.arange(20).reshape(4, 5))
print(np.arange(20).reshape(4,))

[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1
 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
d = np.arange(24).reshape(4, 6)
print(d)
print('index "d[2][3]" >>', d[2][3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
index "d[2][3]" >> 15
